import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import OurTopCategories from "./Components/our-top-categories/OurTopCategories";
import ClientWrapper from "./ClientWrapper";
import NextAuthProvider from "../Providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Roy Mart",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/roy-mart-favicon.png', type: 'image/png' }
    ],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <ClientWrapper>{children}</ClientWrapper>
          <Toaster></Toaster>
        </NextAuthProvider>
      </body>
    </html>
  );
}
